spring.application.name=LaraAPI
# URL para acessar a interface do Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html

# Informações da API (para aparecer no topo da documentação)
springdoc.info.title=LaraAPI - Compilacao e Envio OTA
springdoc.info.version=v1.0.0
springdoc.info.description=API para compilar codigo Arduino e enviar firmware via OTA para ESP32.
springdoc.info.contact.name=Seu Nome
springdoc.info.contact.email=seu.email@exemplo.com

ota.espota-path=/usr/local/bin/espota.py