# Generated by Django 3.2.13 on 2022-07-13 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('experiment', '0002_alter_experiment_type'),
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='time',
        ),
        migrations.AddField(
            model_name='reservation',
            name='end_datetime',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='finished',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='showed_up',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='start_datetime',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='experiment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='experiment', to='experiment.experiment'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
