# Generated by Django 3.2.13 on 2022-07-14 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20220713_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='end_datetime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='start_datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
